name: Firebase integration Spring-boot build

on:
  push:
    branches: [ "main", "feature/*", "fix/*", "refactor/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Build Projetct
      run: mvn clean install -DskipTests
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}} 
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker Image
      run: docker build -t lukkasmatheu/filself-ms .
    - name: Push Image Docker
      run: docker push lukkasmatheu/filself-ms
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
        - name: Pull Image from docker hub
          run: docker pull lukkasmatheu/filself-ms:latest
        - name: run docker container
          run: docker run -d -p 8080:8080 -e FIREBASE_PRIVATE_KEY='${{FIREBASE_PRIVATE_KEY}}' -e FIREBASE_WEB_API_KEY='${{FIREBASE_WEB_API_KEY}}' --name deploy_fiself lukkasmatheu/filself-ms
    
