name: Firebase integration Spring-boot build

on:
  push:
    branches: [ "main", "feature/*", "fix/*", "refactor/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Build Projetct
      run: mvn clean install -DskipTests
    - name: Login Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker Image
      run: docker build -t lukkasmatheu/filself-ms .
    - name: Push Image Docker
      run: docker push lukkasmatheu/filself-ms
